name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  main:
    name: Nx Cloud - Main Job
    uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.11.3
    with:
      main-branch-name: main
      number-of-agents: 3
      init-commands: |
        npx nx-cloud start-ci-run --stop-agents-after="build" --agent-count=3
      parallel-commands: |
        npx nx-cloud record -- npx nx format:check
      parallel-commands-on-agents: |
        npx nx affected --target=lint --parallel=3
        npx nx affected --target=test --parallel=3 --ci --code-coverage
        npx nx affected --target=build --parallel=3
  e2e:
    name: Nx Cloud - E2E Job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: |
          npm ci
          npx nx build api -c=production
      - name: Docker Compose
        run: |
          docker-compose -f compose.test.yml up -d
      - name: Wait for services
        run: |
          npx wait-on http://localhost:3000
      - name: Run E2E tests
        run: |
          npx nx e2e api-e2e
      - name: Docker Compose down
        run: |
          docker-compose -f compose.test.yml down
  agents:
    name: Nx Cloud - Agents
    uses: nrwl/ci/.github/workflows/nx-cloud-agents.yml@v0.11.3
    with:
      number-of-agents: 3
