name: Tag

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Tag Job
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npx -y semantic-release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
